### ISSUE TITLE
ピンをタッチして詳細ページを表示する

### ISSUE THREAD

**Issue by tttkouyou** [ISC-MakeIT/PoiMap_v2#15]
タッチするピンごとに詳細ページに表示する情報が違うので工夫が必要

**Comment by isshun226** [comment]
まず工夫というか普通に配列展開してする際に情報突っ込めばいいのと
issue立てた意図を書いてくれい・・・

**Comment by tttkouyou** [comment]
私的にやり方が思い浮かばないものだったので問題だと考えました。
先ほどもissuesを使えと言われたので、今が使う時だと判断しました。

**Comment by isshun226** [comment]
普通にディスコでレスしてるしがっつりオンラインなんだから直接聞けばいいのでは・・・？
API関連の質問の方も反応ないし、チャットとissueの使い分けしっかりね
